### ISSUE TITLE
foundation-sites 6.3 breaks build

### ISSUE THREAD

**Issue by aexmachina** [acoustep/ember-cli-foundation-6-sass#44] opened 2016-12-26 10:48 UTC
foundation-sites 6.3 now imports SCSS from the `_vendor/` directory using `@import "../_vendor/normalize-scss/sass/normalize";`. This isn't supported by the current broccoli config, because `../_vendor` isn't in the tree.

One solution would be to change `index.js`:

```js
var foundationPath = path.join(app.bowerDirectory, 'foundation-sites');
```

But then everyone would have to update their SCSS to `@import 'scss/foundation'`. Not sure what the best solution is here - might need to use some Broccoli magic to make this work. In the meantime we might want to use a version specifier that avoids users getting v6.3.

**Comment by aexmachina** [comment] 2016-12-26 10:50
My workaround for now is to change `bower.json` to use `"foundation-sites": "~6.2.3"` to avoid v6.3.

**Comment by bravo-kernel** [comment] 2016-12-26 12:58
Looks like a dupe of https://github.com/acoustep/ember-cli-foundation-6-sass/issues/40

**Comment by GCheung55** [comment] 2017-01-04 00:19
Perhaps update `index.js` to determine the correct path depending on what version of `foundation-sites` is installed?

**Closed** 2017-01-07 12:17 UTC
