### ISSUE TITLE
On initial install, add 'broccoli-sass-source-maps' as dependency

### ISSUE THREAD

**Issue by ccbergstrom** [acoustep/ember-cli-foundation-6-sass#43] opened 2016-12-24 15:06 UTC
I've created a new ember 2.10 app, installed [ember-cli-sass](https://github.com/aexmachina/ember-cli-sass), ran `ember server` to confirm that 2.10 works with sass, then installed ember-cli-6-foundation-sass, and tried to run `ember g ember-cli-6-foundation-sass` but I get the following error:
```
Cannot find module 'broccoli-sass-source-maps'
Error: Cannot find module 'broccoli-sass-source-maps'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> ({{currentDirectory}}/node_modules/ember-cli-sass/index.js:1:82)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

I can run `npm install --save-dev brocolli-sass-source-maps` separately & re-run `ember g ember-cli-6-foundation-sass`, and it passes, but figure this should be added to initial install.

**Comment by GCheung55** [comment] 2017-01-09 02:04
@ccbergstrom Interesting issue. `ember-cli-sass` installs `broccoli-sass-source-maps` as a dependency. and `ember-cli-foundation-6-sass` doesn't because it doesn't directly use it.

I wonder if the issue is with the version of `ember-cli-sass` that the blueprint installs, which is `^5.1.0`. The new version of `ember-cli-sass` is `6.0.0`.

Needless to say, `ember-cli-foundation-6-sass` needs to update the blueprint to install the appropriate version.

**Comment by GCheung55** [comment] 2017-01-09 18:22
@ccbergstrom I've created a branch where the addon should install `ember-cli-sass`@6.0.0. Can you try to see if that helps you?

https://github.com/gcheung55/ember-cli-foundation-6-sass/tree/update-ember-cli-sass

**Comment by GCheung55** [comment] 2017-09-25 21:23
I'm closing this issue because there hasn't been any submitter response. Please file another issue if this is still a problem.

**Closed by GCheung55** 2017-09-25 21:23 UTC
